import { AuditAction } from '../types/audit';
import {
  SettlementBatch,
  SettlementBatchDetail,
  SettlementBatchFilters,
  SettlementLine,
} from '../types/transaction';
import { formatDate } from './formatters';

export interface ExportScopeSummary {
  portalName: string;
  scopeLabel: string;
  mdaName: string;
  collectionCode: string;
  serviceCode: string;
  batchId?: string;
  generatedAt: string;
  generatedBy: string;
  dateRangeLabel: string;
}

interface PdfColumn {
  label: string;
  x: number;
}

function escapeCsvCell(value: string) {
  const normalized = value.replace(/"/g, '""');
  return /[",\n]/.test(normalized) ? `"${normalized}"` : normalized;
}

function sanitizeFilenamePart(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function escapePdfText(value: string) {
  return value.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

function formatAmountForPdf(amount: number) {
  return `NGN ${amount.toLocaleString('en-NG', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

function buildPdfTextBlock(lines: Array<{ text: string; x: number; y: number; size?: number }>) {
  return lines
    .map((line) => `BT /F1 ${line.size ?? 10} Tf 1 0 0 1 ${line.x} ${line.y} Tm (${escapePdfText(line.text)}) Tj ET`)
    .join('\n');
}

function createTabularPdfBlob(options: {
  title: string;
  scope: ExportScopeSummary;
  columns: PdfColumn[];
  rows: string[][];
  extraSummaryLines?: string[];
}) {
  const rowsPerPage = 17;
  const pages = Math.max(1, Math.ceil(options.rows.length / rowsPerPage));
  const objects: string[] = [];
  const pageObjectIds: number[] = [];
  const contentObjectIds: number[] = [];

  const fontObjectId = 1;
  const pagesObjectId = 2;
  let nextObjectId = 3;

  for (let pageIndex = 0; pageIndex < pages; pageIndex += 1) {
    pageObjectIds.push(nextObjectId);
    contentObjectIds.push(nextObjectId + 1);
    nextObjectId += 2;
  }

  objects[fontObjectId] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';
  objects[pagesObjectId] = `<< /Type /Pages /Count ${pages} /Kids [${pageObjectIds.map((id) => `${id} 0 R`).join(' ')}] >>`;

  for (let pageIndex = 0; pageIndex < pages; pageIndex += 1) {
    const pageObjectId = pageObjectIds[pageIndex];
    const contentObjectId = contentObjectIds[pageIndex];
    const pageRows = options.rows.slice(pageIndex * rowsPerPage, (pageIndex + 1) * rowsPerPage);

    const lines = [
      { text: options.scope.portalName, x: 40, y: 785, size: 18 },
      { text: options.title, x: 40, y: 764, size: 12 },
      { text: `Scope: ${options.scope.scopeLabel}`, x: 40, y: 738, size: 10 },
      { text: `MDA: ${options.scope.mdaName}`, x: 40, y: 723, size: 10 },
      { text: `Collection Code: ${options.scope.collectionCode}`, x: 40, y: 708, size: 10 },
      { text: `Service Code: ${options.scope.serviceCode}`, x: 260, y: 708, size: 10 },
      { text: `Date Range: ${options.scope.dateRangeLabel}`, x: 40, y: 693, size: 10 },
      { text: `Generated At: ${options.scope.generatedAt}`, x: 40, y: 678, size: 10 },
      { text: `Generated By: ${options.scope.generatedBy}`, x: 320, y: 678, size: 10 },
    ];

    options.extraSummaryLines?.forEach((summaryLine, index) => {
      lines.push({
        text: summaryLine,
        x: index % 2 === 0 ? 40 : 320,
        y: 662 - Math.floor(index / 2) * 15,
        size: 10,
      });
    });

    const headerOffset = Math.max(0, ((options.extraSummaryLines?.length ?? 0) - 1) / 2) * 15;
    const tableHeaderY = 600 - headerOffset;

    options.columns.forEach((column) => {
      lines.push({
        text: column.label,
        x: column.x,
        y: tableHeaderY,
        size: 9,
      });
    });

    pageRows.forEach((row, rowIndex) => {
      const y = tableHeaderY - 24 - rowIndex * 30;
      row.forEach((cell, cellIndex) => {
        lines.push({
          text: cell.slice(0, 24),
          x: options.columns[cellIndex].x,
          y,
          size: 8,
        });
      });
    });

    lines.push({
      text: `Page ${pageIndex + 1} of ${pages}`,
      x: 500,
      y: 30,
      size: 9,
    });

    const contentStream = buildPdfTextBlock(lines);
    objects[contentObjectId] = `<< /Length ${contentStream.length} >>\nstream\n${contentStream}\nendstream`;
    objects[pageObjectId] =
      `<< /Type /Page /Parent ${pagesObjectId} 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${fontObjectId} 0 R >> >> /Contents ${contentObjectId} 0 R >>`;
  }

  const catalogObjectId = objects.length;
  const output = ['%PDF-1.4\n'];
  const offsets: number[] = [0];

  for (let objectId = 1; objectId <= catalogObjectId; objectId += 1) {
    const objectBody =
      objectId === catalogObjectId
        ? `${catalogObjectId} 0 obj\n<< /Type /Catalog /Pages ${pagesObjectId} 0 R >>\nendobj\n`
        : `${objectId} 0 obj\n${objects[objectId]}\nendobj\n`;

    offsets[objectId] = output.join('').length;
    output.push(objectBody);
  }

  const xrefOffset = output.join('').length;
  output.push(`xref\n0 ${catalogObjectId + 1}\n`);
  output.push('0000000000 65535 f \n');

  for (let objectId = 1; objectId <= catalogObjectId; objectId += 1) {
    output.push(`${String(offsets[objectId]).padStart(10, '0')} 00000 n \n`);
  }

  output.push(
    `trailer\n<< /Size ${catalogObjectId + 1} /Root ${catalogObjectId} 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`
  );

  return new Blob([output.join('')], { type: 'application/pdf' });
}

export function createSettlementBatchCsvBlob(batches: SettlementBatch[]) {
  const headers = [
    'Settled Date',
    'Batch ID',
    'MDA Name',
    'Collection Code',
    'Service Code',
    'Item Count',
    'Total Amount',
    'Aggregator ID',
  ];

  const rows = batches.map((batch) =>
    [
      formatDate(batch.settledDate),
      batch.batchId,
      batch.mdaName,
      batch.collectionCode,
      batch.serviceCode,
      String(batch.itemCount),
      batch.totalAmount.toFixed(2),
      batch.aggregatorId,
    ]
      .map((cell) => escapeCsvCell(cell))
      .join(',')
  );

  return new Blob([[headers.join(','), ...rows].join('\n')], {
    type: 'text/csv;charset=utf-8',
  });
}

export function createSettlementLineCsvBlob(lines: SettlementLine[]) {
  const headers = [
    'Settled Date',
    'Batch ID',
    'Bank',
    'Account Number',
    'Account Name',
    'Amount',
    'Collection Code',
    'Service Code',
    'Aggregator ID',
  ];

  const rows = lines.map((line) =>
    [
      formatDate(line.settledDate),
      line.batchId,
      line.bankName,
      line.accountNumber,
      line.accountName,
      line.amount.toFixed(2),
      line.collectionCode,
      line.serviceCode,
      line.aggregatorId,
    ]
      .map((cell) => escapeCsvCell(cell))
      .join(',')
  );

  return new Blob([[headers.join(','), ...rows].join('\n')], {
    type: 'text/csv;charset=utf-8',
  });
}

export function createSettlementBatchListPdfBlob(
  batches: SettlementBatch[],
  scope: ExportScopeSummary,
) {
  return createTabularPdfBlob({
    title: 'Settlement Batch Export Report',
    scope,
    columns: [
      { label: 'Settled Date', x: 40 },
      { label: 'Batch ID', x: 110 },
      { label: 'MDA', x: 190 },
      { label: 'Scope', x: 300 },
      { label: 'Items', x: 430 },
      { label: 'Total', x: 490 },
    ],
    rows: batches.map((batch) => [
      formatDate(batch.settledDate),
      batch.batchId,
      batch.mdaName,
      `${batch.collectionCode}/${batch.serviceCode}`,
      String(batch.itemCount),
      formatAmountForPdf(batch.totalAmount),
    ]),
  });
}

export function createSettlementBatchDetailPdfBlob(
  detail: SettlementBatchDetail,
  scope: ExportScopeSummary,
) {
  return createTabularPdfBlob({
    title: 'Settlement Batch Detail Report',
    scope,
    extraSummaryLines: [
      `Batch ID: ${detail.batch.batchId}`,
      `Item Count: ${detail.batch.itemCount}`,
      `Settled Date: ${formatDate(detail.batch.settledDate)}`,
      `Batch Total: ${formatAmountForPdf(detail.batch.totalAmount)}`,
    ],
    columns: [
      { label: 'Bank', x: 40 },
      { label: 'Account Number', x: 190 },
      { label: 'Account Name', x: 320 },
      { label: 'Amount', x: 500 },
    ],
    rows: detail.lines.map((line) => [
      line.bankName,
      line.accountNumber,
      line.accountName,
      formatAmountForPdf(line.amount),
    ]),
  });
}

export function triggerFileDownload(blob: Blob, filename: string) {
  const objectUrl = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = objectUrl;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(objectUrl);
}

export function buildExportFilename(
  format: 'csv' | 'pdf',
  scopeLabel: string,
  generatedAt: string,
) {
  const datePart = generatedAt.slice(0, 10);
  return `tsa-${sanitizeFilenamePart(scopeLabel)}-${datePart}.${format}`;
}

export function buildExportDateRangeLabel(filters: SettlementBatchFilters) {
  if (filters.from && filters.to) {
    return `${formatDate(filters.from)} to ${formatDate(filters.to)}`;
  }

  if (filters.from) {
    return `From ${formatDate(filters.from)}`;
  }

  if (filters.to) {
    return `Up to ${formatDate(filters.to)}`;
  }

  return 'All dates';
}

export function buildSettlementExportAuditDetails(
  action: AuditAction,
  target: { type: 'batch-list'; count: number } | { type: 'batch-detail'; batchId: string; count: number },
) {
  if (target.type === 'batch-detail') {
    return `${action === 'export_csv' ? 'CSV' : 'PDF'} settlement export generated for batch ${target.batchId} with ${target.count} settlement lines.`;
  }

  return `${action === 'export_csv' ? 'CSV' : 'PDF'} settlement batch export generated with ${target.count} batches.`;
}
