import { AuditAction } from '../types/audit';
import { Transaction, TransactionFilters } from '../types/transaction';
import { formatChannel, formatDate, formatDateTime, formatStatus } from './formatters';

export interface ExportScopeSummary {
  portalName: string;
  scopeLabel: string;
  mdaName: string;
  collectionCode: string;
  serviceCode: string;
  generatedAt: string;
  generatedBy: string;
  dateRangeLabel: string;
}

function escapeCsvCell(value: string) {
  const normalized = value.replace(/"/g, '""');
  return /[",\n]/.test(normalized) ? `"${normalized}"` : normalized;
}

function sanitizeFilenamePart(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function escapePdfText(value: string) {
  return value.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

function formatAmountForPdf(amount: number) {
  return `NGN ${amount.toLocaleString('en-NG', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

function buildPdfTextBlock(lines: Array<{ text: string; x: number; y: number; size?: number }>) {
  return lines
    .map((line) => `BT /F1 ${line.size ?? 10} Tf 1 0 0 1 ${line.x} ${line.y} Tm (${escapePdfText(line.text)}) Tj ET`)
    .join('\n');
}

export function createCsvContent(transactions: Transaction[]) {
  const headers = [
    'Reference',
    'Payer Name',
    'Payer Account',
    'Payer Bank',
    'Amount',
    'Channel',
    'Settlement Date',
    'Status',
    'Collection Code',
    'Service Code',
    'Aggregator ID',
    'Narration',
    'Settlement Batch',
  ];

  const rows = transactions.map((transaction) =>
    [
      transaction.reference,
      transaction.payerName,
      transaction.payerAccount,
      transaction.payerBank,
      transaction.amount.toFixed(2),
      formatChannel(transaction.channel),
      formatDateTime(transaction.settlementDate),
      formatStatus(transaction.status),
      transaction.collectionCode,
      transaction.serviceCode,
      transaction.aggregatorId,
      transaction.narration,
      transaction.settlementBatch ?? '',
    ]
      .map((cell) => escapeCsvCell(cell))
      .join(',')
  );

  return [headers.join(','), ...rows].join('\n');
}

export function createCsvBlob(transactions: Transaction[]) {
  return new Blob([createCsvContent(transactions)], {
    type: 'text/csv;charset=utf-8',
  });
}

export function createPdfBlob(transactions: Transaction[], scope: ExportScopeSummary) {
  const rowsPerPage = 16;
  const pages = Math.max(1, Math.ceil(transactions.length / rowsPerPage));
  const objects: string[] = [];
  const pageObjectIds: number[] = [];
  const contentObjectIds: number[] = [];

  const fontObjectId = 1;
  const pagesObjectId = 2;
  let nextObjectId = 3;

  for (let pageIndex = 0; pageIndex < pages; pageIndex += 1) {
    const pageObjectId = nextObjectId;
    const contentObjectId = nextObjectId + 1;
    pageObjectIds.push(pageObjectId);
    contentObjectIds.push(contentObjectId);
    nextObjectId += 2;
  }

  const pageEntries = pageObjectIds
    .map((pageObjectId) => `${pageObjectId} 0 R`)
    .join(' ');

  objects[fontObjectId] = `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`;
  objects[pagesObjectId] = `<< /Type /Pages /Count ${pages} /Kids [${pageEntries}] >>`;

  const tableHeaderY = 610;
  const columnXs = [40, 130, 240, 330, 430, 510];

  for (let pageIndex = 0; pageIndex < pages; pageIndex += 1) {
    const pageObjectId = pageObjectIds[pageIndex];
    const contentObjectId = contentObjectIds[pageIndex];
    const pageTransactions = transactions.slice(pageIndex * rowsPerPage, (pageIndex + 1) * rowsPerPage);

    const lines = [
      { text: scope.portalName, x: 40, y: 785, size: 18 },
      { text: 'Transaction Export Report', x: 40, y: 764, size: 12 },
      { text: `Scope: ${scope.scopeLabel}`, x: 40, y: 738, size: 10 },
      { text: `MDA: ${scope.mdaName}`, x: 40, y: 723, size: 10 },
      { text: `Collection Code: ${scope.collectionCode}`, x: 40, y: 708, size: 10 },
      { text: `Service Code: ${scope.serviceCode}`, x: 260, y: 708, size: 10 },
      { text: `Date Range: ${scope.dateRangeLabel}`, x: 40, y: 693, size: 10 },
      { text: `Generated At: ${scope.generatedAt}`, x: 40, y: 678, size: 10 },
      { text: `Generated By: ${scope.generatedBy}`, x: 320, y: 678, size: 10 },
      { text: 'Reference', x: columnXs[0], y: tableHeaderY, size: 9 },
      { text: 'Payer', x: columnXs[1], y: tableHeaderY, size: 9 },
      { text: 'Amount', x: columnXs[2], y: tableHeaderY, size: 9 },
      { text: 'Channel', x: columnXs[3], y: tableHeaderY, size: 9 },
      { text: 'Settlement Date', x: columnXs[4], y: tableHeaderY, size: 9 },
      { text: 'Status', x: columnXs[5], y: tableHeaderY, size: 9 },
    ];

    pageTransactions.forEach((transaction, rowIndex) => {
      const y = tableHeaderY - 24 - rowIndex * 30;
      lines.push(
        { text: transaction.reference.slice(0, 18), x: columnXs[0], y, size: 8 },
        { text: transaction.payerName.slice(0, 20), x: columnXs[1], y, size: 8 },
        { text: formatAmountForPdf(transaction.amount), x: columnXs[2], y, size: 8 },
        { text: formatChannel(transaction.channel), x: columnXs[3], y, size: 8 },
        { text: formatDate(transaction.settlementDate), x: columnXs[4], y, size: 8 },
        { text: formatStatus(transaction.status), x: columnXs[5], y, size: 8 }
      );
    });

    lines.push({
      text: `Page ${pageIndex + 1} of ${pages}`,
      x: 500,
      y: 30,
      size: 9,
    });

    const contentStream = buildPdfTextBlock(lines);
    objects[contentObjectId] = `<< /Length ${contentStream.length} >>\nstream\n${contentStream}\nendstream`;
    objects[pageObjectId] =
      `<< /Type /Page /Parent ${pagesObjectId} 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${fontObjectId} 0 R >> >> /Contents ${contentObjectId} 0 R >>`;
  }

  const pdfParts = ['%PDF-1.4\n'];
  const offsets: number[] = [0];

  for (let objectId = 1; objectId < objects.length; objectId += 1) {
    const objectBody = `${objectId} 0 obj\n${objects[objectId]}\nendobj\n`;
    offsets[objectId] = pdfParts.join('').length;
    pdfParts.push(objectBody);
  }

  const xrefOffset = pdfParts.join('').length;
  pdfParts.push(`xref\n0 ${objects.length}\n`);
  pdfParts.push('0000000000 65535 f \n');

  for (let objectId = 1; objectId < objects.length; objectId += 1) {
    pdfParts.push(`${String(offsets[objectId]).padStart(10, '0')} 00000 n \n`);
  }

  pdfParts.push(
    `trailer\n<< /Size ${objects.length} /Root ${objects.length} 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`
  );

  const catalogObjectId = objects.length;
  pdfParts.splice(objects.length, 0, `${catalogObjectId} 0 obj\n<< /Type /Catalog /Pages ${pagesObjectId} 0 R >>\nendobj\n`);

  const reconstructed = ['%PDF-1.4\n'];
  const reconstructedOffsets: number[] = [0];

  for (let objectId = 1; objectId <= catalogObjectId; objectId += 1) {
    let objectBody: string;

    if (objectId === catalogObjectId) {
      objectBody = `${catalogObjectId} 0 obj\n<< /Type /Catalog /Pages ${pagesObjectId} 0 R >>\nendobj\n`;
    } else {
      objectBody = `${objectId} 0 obj\n${objects[objectId]}\nendobj\n`;
    }

    reconstructedOffsets[objectId] = reconstructed.join('').length;
    reconstructed.push(objectBody);
  }

  const reconstructedXrefOffset = reconstructed.join('').length;
  reconstructed.push(`xref\n0 ${catalogObjectId + 1}\n`);
  reconstructed.push('0000000000 65535 f \n');

  for (let objectId = 1; objectId <= catalogObjectId; objectId += 1) {
    reconstructed.push(`${String(reconstructedOffsets[objectId]).padStart(10, '0')} 00000 n \n`);
  }

  reconstructed.push(
    `trailer\n<< /Size ${catalogObjectId + 1} /Root ${catalogObjectId} 0 R >>\nstartxref\n${reconstructedXrefOffset}\n%%EOF`
  );

  return new Blob([reconstructed.join('')], { type: 'application/pdf' });
}

export function triggerFileDownload(blob: Blob, filename: string) {
  const objectUrl = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = objectUrl;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(objectUrl);
}

export function buildExportFilename(
  format: 'csv' | 'pdf',
  scopeLabel: string,
  generatedAt: string
) {
  const datePart = generatedAt.slice(0, 10);
  return `tsa-${sanitizeFilenamePart(scopeLabel)}-${datePart}.${format}`;
}

export function buildExportDateRangeLabel(filters: TransactionFilters) {
  if (filters.from && filters.to) {
    return `${formatDate(filters.from)} to ${formatDate(filters.to)}`;
  }

  if (filters.from) {
    return `From ${formatDate(filters.from)}`;
  }

  if (filters.to) {
    return `Up to ${formatDate(filters.to)}`;
  }

  return 'All dates';
}

export function buildExportAuditDetails(
  action: AuditAction,
  scopeLabel: string,
  count: number
) {
  return `${action === 'export_csv' ? 'CSV' : 'PDF'} export generated for ${scopeLabel} with ${count} transactions.`;
}
